// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products/{id}": {
      "get": {
        "summary": "getProductById",
        "description": "",
        "operationId": "getProductById.get.products/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/products": {
      "get": {
        "summary": "getAllProducts",
        "description": "",
        "operationId": "getAllProducts.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/Products"
            }
          },
          "404": {
            "description": "Products not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/product": {
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post.product",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/Products"
            }
          },
          "404": {
            "description": "Products not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    }
  },
  "definitions": {
    "ProductInterface": {
      "properties": {
        "id": {
          "title": "ProductInterface.id",
          "type": "number"
        },
        "title": {
          "title": "ProductInterface.title",
          "type": "string"
        },
        "description": {
          "title": "ProductInterface.description",
          "type": "string"
        },
        "image": {
          "title": "ProductInterface.image",
          "type": "string"
        },
        "rating": {
          "title": "ProductInterface.rating",
          "type": "number"
        },
        "released": {
          "title": "ProductInterface.released",
          "type": "string"
        },
        "platforms": {
          "title": "ProductInterface.platforms",
          "type": "string"
        },
        "genres": {
          "title": "ProductInterface.genres",
          "type": "string"
        },
        "price": {
          "title": "ProductInterface.price",
          "type": "number"
        }
      },
      "required": [
        "id",
        "title",
        "description",
        "image",
        "rating",
        "released",
        "platforms",
        "genres",
        "price"
      ],
      "additionalProperties": false,
      "title": "ProductInterface",
      "type": "object"
    },
    "StockInterface": {
      "properties": {
        "id": {
          "title": "StockInterface.id",
          "type": "number"
        },
        "product_id": {
          "title": "StockInterface.product_id",
          "type": "number"
        },
        "count": {
          "title": "StockInterface.count",
          "type": "number"
        }
      },
      "required": [
        "id",
        "product_id",
        "count"
      ],
      "additionalProperties": false,
      "title": "StockInterface",
      "type": "object"
    },
    "Product": {
      "$ref": "#/definitions/ProductInterface",
      "title": "Product"
    },
    "Products": {
      "items": {
        "$ref": "#/definitions/Product",
        "title": "Products.[]"
      },
      "title": "Products.[]",
      "type": "array"
    },
    "AvailableProduct": {
      "allOf": [
        {
          "$ref": "#/definitions/ProductInterface"
        },
        {
          "$ref": "#/definitions/StockInterface"
        }
      ],
      "title": "AvailableProduct"
    },
    "AvailableProducts": {
      "items": {
        "$ref": "#/definitions/AvailableProduct",
        "title": "AvailableProducts.[]"
      },
      "title": "AvailableProducts.[]",
      "type": "array"
    }
  },
  "securityDefinitions": {},
  "host": "xck7eiwcuj.execute-api.us-east-1.amazonaws.com/dev",
  "schemes": [
    "https",
    "ws",
    "wss"
  ]
};